//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductInOrder = new HashSet<ProductInOrder>();
        }
    
        public int Id { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public int UnitId { get; set; }
        public decimal Price { get; set; }
        public int ProviderId { get; set; }
        public int ProducerId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public decimal AmountInStock { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<ProductInOrder> ProductInOrder { get; set; }
    }
}
